try:
    print(x)
except:
    print("An exception has occurred")